disabled = false
languageCode = "it"
languageName = "Italiano"
weight = 1
title = "Cuorpugnale"

[params]
  displayName = "IT"
  isoCode = "it"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/Daggerheart_logo_2025.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "CUORPUGNALE"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Cuorpugnale"
  headline = "Un podcast ideato da Walid Husein e Gianluca Danaro"
  links = [
    { youtube = "https://www.youtube.com/@Cuorpugnale" },
    { link = "https://acheron.it" },
  ]
